import jsPDF from "jspdf";

// ─── Storyboard PDF ─────────────────────────────────────────────────────────
export function exportStoryboardPdf(data: {
  title: string;
  synopsis?: string;
  totalDuration?: number;
  style?: string;
  scenes: Array<{
    sceneNumber: number;
    duration: number;
    cameraAngle: string;
    cameraMovement: string;
    visualDescription: string;
    narration?: string;
    mood: string;
    transition: string;
    imageUrl?: string;
  }>;
}) {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;

  // Title page
  doc.setFillColor(15, 15, 25);
  doc.rect(0, 0, pageW, pageH, "F");

  doc.setTextColor(200, 180, 255);
  doc.setFontSize(32);
  doc.text(data.title || "Storyboard", pageW / 2, 60, { align: "center" });

  if (data.synopsis) {
    doc.setFontSize(12);
    doc.setTextColor(160, 160, 180);
    const synLines = doc.splitTextToSize(data.synopsis, pageW - margin * 4);
    doc.text(synLines, pageW / 2, 80, { align: "center" });
  }

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 140);
  const meta: string[] = [];
  if (data.style) meta.push(`Style: ${data.style}`);
  if (data.totalDuration) meta.push(`Duration: ${data.totalDuration}s`);
  meta.push(`Scenes: ${data.scenes.length}`);
  doc.text(meta.join("  |  "), pageW / 2, 100, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(80, 80, 100);
  doc.text(`Generated by DreamForgeX Video Studio  •  ${new Date().toLocaleDateString()}`, pageW / 2, pageH - 15, { align: "center" });

  // Scene pages
  for (const scene of data.scenes) {
    doc.addPage("a4", "landscape");
    doc.setFillColor(15, 15, 25);
    doc.rect(0, 0, pageW, pageH, "F");

    // Scene header
    doc.setFillColor(40, 30, 80);
    doc.roundedRect(margin, margin, pageW - margin * 2, 14, 3, 3, "F");
    doc.setTextColor(200, 180, 255);
    doc.setFontSize(14);
    doc.text(`Scene ${scene.sceneNumber}`, margin + 5, margin + 9);

    doc.setFontSize(9);
    doc.setTextColor(160, 160, 180);
    const headerInfo = [`${scene.duration}s`, scene.mood, scene.transition].filter(Boolean).join("  •  ");
    doc.text(headerInfo, pageW - margin - 5, margin + 9, { align: "right" });

    let y = margin + 22;

    // Visual description
    doc.setFontSize(8);
    doc.setTextColor(100, 90, 150);
    doc.text("VISUAL DESCRIPTION", margin, y);
    y += 5;
    doc.setFontSize(10);
    doc.setTextColor(220, 220, 230);
    const visLines = doc.splitTextToSize(scene.visualDescription, pageW - margin * 2);
    doc.text(visLines, margin, y);
    y += visLines.length * 5 + 6;

    // Camera
    doc.setFontSize(8);
    doc.setTextColor(100, 90, 150);
    doc.text("CAMERA", margin, y);
    y += 5;
    doc.setFontSize(9);
    doc.setTextColor(180, 180, 200);
    doc.text(`Angle: ${scene.cameraAngle}  |  Movement: ${scene.cameraMovement}`, margin, y);
    y += 8;

    // Narration
    if (scene.narration) {
      doc.setFontSize(8);
      doc.setTextColor(100, 90, 150);
      doc.text("NARRATION", margin, y);
      y += 5;
      doc.setFontSize(9);
      doc.setTextColor(180, 170, 130);
      const narLines = doc.splitTextToSize(`"${scene.narration}"`, pageW - margin * 2);
      doc.text(narLines, margin, y);
      y += narLines.length * 4.5 + 6;
    }

    // Mood & Transition
    doc.setFontSize(8);
    doc.setTextColor(100, 90, 150);
    doc.text("MOOD & TRANSITION", margin, y);
    y += 5;
    doc.setFontSize(9);
    doc.setTextColor(180, 180, 200);
    doc.text(`Mood: ${scene.mood}  |  Transition: ${scene.transition}`, margin, y);
  }

  doc.save(`${(data.title || "storyboard").replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}.pdf`);
}

// ─── Script PDF ─────────────────────────────────────────────────────────────
export function exportScriptPdf(data: {
  title: string;
  logline?: string;
  targetDuration?: number;
  format?: string;
  tone?: string;
  productionBudget?: string;
  equipmentNeeded?: string[];
  scenes: Array<{
    sceneNumber: number;
    startTime: string;
    endTime: string;
    location: string;
    visualDescription: string;
    cameraDirection: string;
    narration?: string;
    dialogue?: string;
    soundDesign?: string;
    productionNotes?: string;
  }>;
}) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;

  // Title page
  doc.setFillColor(15, 15, 25);
  doc.rect(0, 0, pageW, pageH, "F");

  doc.setTextColor(200, 180, 255);
  doc.setFontSize(28);
  doc.text(data.title || "Video Script", pageW / 2, 80, { align: "center" });

  if (data.logline) {
    doc.setFontSize(11);
    doc.setTextColor(160, 160, 180);
    const logLines = doc.splitTextToSize(data.logline, contentW);
    doc.text(logLines, pageW / 2, 95, { align: "center" });
  }

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 140);
  const meta: string[] = [];
  if (data.format) meta.push(`Format: ${data.format}`);
  if (data.tone) meta.push(`Tone: ${data.tone}`);
  if (data.targetDuration) meta.push(`Duration: ${data.targetDuration}s`);
  meta.push(`Scenes: ${data.scenes.length}`);
  doc.text(meta.join("  |  "), pageW / 2, 115, { align: "center" });

  if (data.productionBudget) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 120);
    doc.text(`Budget: ${data.productionBudget}`, pageW / 2, 125, { align: "center" });
  }

  doc.setFontSize(8);
  doc.setTextColor(80, 80, 100);
  doc.text(`Generated by DreamForgeX Video Studio  •  ${new Date().toLocaleDateString()}`, pageW / 2, pageH - 15, { align: "center" });

  // Scene pages
  for (const scene of data.scenes) {
    doc.addPage("a4", "portrait");
    doc.setFillColor(15, 15, 25);
    doc.rect(0, 0, pageW, pageH, "F");

    // Scene header bar
    doc.setFillColor(40, 30, 80);
    doc.roundedRect(margin, margin, contentW, 16, 3, 3, "F");
    doc.setTextColor(200, 180, 255);
    doc.setFontSize(12);
    doc.text(`SCENE ${scene.sceneNumber}`, margin + 5, margin + 10);
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 180);
    doc.text(`${scene.startTime} — ${scene.endTime}  |  ${scene.location}`, pageW - margin - 5, margin + 10, { align: "right" });

    let y = margin + 24;

    const addSection = (label: string, text: string, color: [number, number, number] = [220, 220, 230]) => {
      if (y > pageH - 30) {
        doc.addPage("a4", "portrait");
        doc.setFillColor(15, 15, 25);
        doc.rect(0, 0, pageW, pageH, "F");
        y = margin;
      }
      doc.setFontSize(7);
      doc.setTextColor(100, 90, 150);
      doc.text(label, margin, y);
      y += 4;
      doc.setFontSize(9);
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text, contentW);
      doc.text(lines, margin, y);
      y += lines.length * 4.5 + 6;
    };

    addSection("VISUAL DESCRIPTION", scene.visualDescription);
    addSection("CAMERA DIRECTION", scene.cameraDirection, [180, 200, 220]);

    if (scene.narration) {
      addSection("NARRATION", `"${scene.narration}"`, [180, 170, 130]);
    }
    if (scene.dialogue) {
      addSection("DIALOGUE", scene.dialogue, [170, 180, 200]);
    }
    if (scene.soundDesign) {
      addSection("SOUND DESIGN", scene.soundDesign, [150, 160, 170]);
    }
    if (scene.productionNotes) {
      addSection("PRODUCTION NOTES", scene.productionNotes, [140, 140, 160]);
    }
  }

  // Equipment page
  if (data.equipmentNeeded && data.equipmentNeeded.length > 0) {
    doc.addPage("a4", "portrait");
    doc.setFillColor(15, 15, 25);
    doc.rect(0, 0, pageW, pageH, "F");

    doc.setTextColor(200, 180, 255);
    doc.setFontSize(16);
    doc.text("Equipment & Production", margin, margin + 10);

    let y = margin + 20;
    doc.setFontSize(9);
    doc.setTextColor(180, 180, 200);
    for (const eq of data.equipmentNeeded) {
      doc.text(`•  ${eq}`, margin + 5, y);
      y += 6;
    }

    if (data.productionBudget) {
      y += 6;
      doc.setFontSize(8);
      doc.setTextColor(100, 90, 150);
      doc.text("BUDGET ESTIMATE", margin, y);
      y += 5;
      doc.setFontSize(9);
      doc.setTextColor(180, 180, 200);
      doc.text(data.productionBudget, margin, y);
    }
  }

  doc.save(`${(data.title || "script").replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}.pdf`);
}
