import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "AI Storyboard Generator — Visual Panels from a Concept | DreamForgeX",
  description: "Describe your video concept and get a shot-by-shot storyboard: visual panels, scene synopses, and pacing notes ready for production.",
  alternates: { canonical: "https://dreamforgex.ai/video-studio/storyboard" },
  openGraph: {
    title: "AI Storyboard Generator — DreamForgeX",
    description: "Concept to shot-by-shot visual storyboard panels, generated by AI.",
  },
};
export default function Layout({ children }: { children: React.ReactNode }) { return children; }
