import { vi, describe, it, expect, beforeEach } from "vitest";

// Mock credit deduction — refineProject now deducts ai-refine credits
// (Phase 39 T0.5 patch) so tests need the stripe mock or they'd try the
// real deductCredits and fail on DB unavailability.
vi.mock("./stripe", async () => {
  const actual = await vi.importActual<any>("./stripe");
  return {
    ...actual,
    deductCredits: vi.fn().mockResolvedValue({ success: true, balance: 1000, needed: 5 }),
  };
});

// Mock the image generation helper
vi.mock("./_core/imageGeneration", () => ({
  generateImage: vi.fn().mockResolvedValue({ url: "https://cdn.example.com/result.png" }),
}));

// Mock the LLM helper
vi.mock("./_core/llm", () => ({
  invokeLLM: vi.fn().mockResolvedValue({
    choices: [{
      message: {
        content: JSON.stringify({
          title: "Refined Mars Expedition",
          scenes: [{ sceneNumber: 1, visualDescription: "Improved scene" }],
        }),
      },
    }],
  }),
}));

// Mock all db functions
const mockCreateVideoProject = vi.fn();
const mockUpdateVideoProject = vi.fn();
const mockGetVideoProject = vi.fn();
const mockListVideoProjects = vi.fn();
const mockDeleteVideoProject = vi.fn();
const mockCreateShareToken = vi.fn();
const mockGetShareToken = vi.fn();
const mockIncrementShareTokenUse = vi.fn();
const mockDeactivateShareToken = vi.fn();
const mockListShareTokens = vi.fn();
const mockAddCollaborator = vi.fn();
const mockListCollaborators = vi.fn();
const mockRemoveCollaborator = vi.fn();
const mockListSharedWithMe = vi.fn();
const mockGetUserCollaboratorRole = vi.fn();
const mockCreateRevision = vi.fn();
const mockListRevisions = vi.fn();
const mockGetRevision = vi.fn();
const mockGetLatestRevisionVersion = vi.fn();

vi.mock("./db", async (importOriginal) => {
  const original = await importOriginal<typeof import("./db")>();
  return {
    ...original,
    createVideoProject: (...args: any[]) => mockCreateVideoProject(...args),
    updateVideoProject: (...args: any[]) => mockUpdateVideoProject(...args),
    getVideoProject: (...args: any[]) => mockGetVideoProject(...args),
    listVideoProjects: (...args: any[]) => mockListVideoProjects(...args),
    deleteVideoProject: (...args: any[]) => mockDeleteVideoProject(...args),
    createShareToken: (...args: any[]) => mockCreateShareToken(...args),
    getShareToken: (...args: any[]) => mockGetShareToken(...args),
    incrementShareTokenUse: (...args: any[]) => mockIncrementShareTokenUse(...args),
    deactivateShareToken: (...args: any[]) => mockDeactivateShareToken(...args),
    listShareTokens: (...args: any[]) => mockListShareTokens(...args),
    addCollaborator: (...args: any[]) => mockAddCollaborator(...args),
    listCollaborators: (...args: any[]) => mockListCollaborators(...args),
    removeCollaborator: (...args: any[]) => mockRemoveCollaborator(...args),
    listSharedWithMe: (...args: any[]) => mockListSharedWithMe(...args),
    getUserCollaboratorRole: (...args: any[]) => mockGetUserCollaboratorRole(...args),
    createRevision: (...args: any[]) => mockCreateRevision(...args),
    listRevisions: (...args: any[]) => mockListRevisions(...args),
    getRevision: (...args: any[]) => mockGetRevision(...args),
    getLatestRevisionVersion: (...args: any[]) => mockGetLatestRevisionVersion(...args),
  };
});

import { appRouter } from "./routers";

const mockCtx = {
  user: {
    id: 1,
    openId: "test-user-123",
    name: "Test Creator",
    email: "test@dreamforge.ai",
    role: "user" as const,
    createdAt: new Date(),
  },
  setCookie: vi.fn(),
  clearCookie: vi.fn(),
};

const mockCtx2 = {
  user: {
    id: 2,
    openId: "test-user-456",
    name: "Collaborator User",
    email: "collab@dreamforge.ai",
    role: "user" as const,
    createdAt: new Date(),
  },
  setCookie: vi.fn(),
  clearCookie: vi.fn(),
};

const caller = appRouter.createCaller(mockCtx as any);
const caller2 = appRouter.createCaller(mockCtx2 as any);

// ─── Collaboration Tests ──────────────────────────────────────────
describe("Collaboration Features", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("videoProject.createShareLink", () => {
    it("should create a viewer share link", async () => {
      // getVideoProject is called to verify ownership
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1, type: "storyboard" });
      mockCreateShareToken.mockResolvedValueOnce({ id: 10, token: "abc123" });

      const result = await caller.videoProject.createShareLink({
        projectId: 1,
        permission: "viewer",
        expiresInHours: 168,
      });

      expect(result.token).toBeTruthy(); // token is generated by crypto.randomUUID, not from mock
      expect(result.id).toBe(10);
      expect(result.permission).toBe("viewer");
      expect(mockCreateShareToken).toHaveBeenCalledWith(
        expect.objectContaining({
          projectId: 1,
          createdBy: 1,
          permission: "viewer",
        })
      );
    });

    it("should create an editor share link", async () => {
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1, type: "storyboard" });
      mockCreateShareToken.mockResolvedValueOnce({ id: 11, token: "def456" });

      const result = await caller.videoProject.createShareLink({
        projectId: 1,
        permission: "editor",
        expiresInHours: 24,
      });

      expect(result.id).toBe(11);
      expect(result.permission).toBe("editor");
    });

    it("should reject if user doesn't own the project", async () => {
      mockGetVideoProject.mockResolvedValueOnce(null);

      await expect(
        caller.videoProject.createShareLink({
          projectId: 999,
          permission: "viewer",
        })
      ).rejects.toThrow("Project not found");
    });
  });

  describe("videoProject.acceptShareLink", () => {
    it("should accept a valid share link and add collaborator", async () => {
      mockGetShareToken.mockResolvedValueOnce({
        id: 10,
        projectId: 1,
        permission: "viewer",
        active: true,
        isActive: true,
        expiresAt: new Date(Date.now() + 86400000),
        useCount: 0,
        maxUses: null,
        createdBy: 1,
      });
      // getVideoProject is called to check if user is owner - return null (not owner)
      mockGetVideoProject.mockResolvedValueOnce(null);
      mockAddCollaborator.mockResolvedValueOnce({ id: 5, action: "added" });
      mockIncrementShareTokenUse.mockResolvedValueOnce(undefined);

      const result = await caller2.videoProject.acceptShareLink({
        token: "abc123",
      });

      expect(result.projectId).toBe(1);
      expect(result.role).toBe("viewer");
      expect(mockAddCollaborator).toHaveBeenCalled();
    });

    it("should return alreadyOwner if user owns the project", async () => {
      mockGetShareToken.mockResolvedValueOnce({
        id: 10,
        projectId: 1,
        permission: "viewer",
        active: true,
        isActive: true,
        expiresAt: new Date(Date.now() + 86400000),
        useCount: 0,
        maxUses: null,
        createdBy: 1,
      });
      // getVideoProject returns project (user is owner)
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1 });

      const result = await caller.videoProject.acceptShareLink({
        token: "abc123",
      });

      expect(result.projectId).toBe(1);
      expect(result.alreadyOwner).toBe(true);
    });

    it("should reject inactive share link", async () => {
      mockGetShareToken.mockResolvedValueOnce({
        id: 10,
        projectId: 1,
        permission: "viewer",
        active: false,
        isActive: false,
        expiresAt: new Date(Date.now() + 86400000),
        useCount: 0,
        maxUses: null,
      });

      await expect(
        caller2.videoProject.acceptShareLink({ token: "inactive-token" })
      ).rejects.toThrow();
    });

    it("should reject if token not found", async () => {
      mockGetShareToken.mockResolvedValueOnce(null);

      await expect(
        caller2.videoProject.acceptShareLink({ token: "nonexistent" })
      ).rejects.toThrow();
    });

    it("should reject expired share link", async () => {
      mockGetShareToken.mockResolvedValueOnce({
        id: 10,
        projectId: 1,
        permission: "viewer",
        active: true,
        isActive: true,
        expiresAt: new Date(Date.now() - 86400000), // expired
        useCount: 0,
        maxUses: null,
      });

      await expect(
        caller2.videoProject.acceptShareLink({ token: "expired-token" })
      ).rejects.toThrow();
    });
  });

  describe("videoProject.listShareTokens", () => {
    it("should list active share tokens for a project", async () => {
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1 });
      mockListShareTokens.mockResolvedValueOnce([
        { id: 10, token: "abc123", permission: "viewer", useCount: 3, isActive: true },
        { id: 11, token: "def456", permission: "editor", useCount: 1, isActive: true },
      ]);

      const result = await caller.videoProject.listShareTokens({ projectId: 1 });

      expect(result).toHaveLength(2);
      expect(result[0].permission).toBe("viewer");
    });

    it("should reject if user doesn't own the project", async () => {
      mockGetVideoProject.mockResolvedValueOnce(null);

      await expect(
        caller.videoProject.listShareTokens({ projectId: 999 })
      ).rejects.toThrow("Project not found");
    });
  });

  describe("videoProject.deactivateShareToken", () => {
    it("should deactivate a share token", async () => {
      mockDeactivateShareToken.mockResolvedValueOnce({ success: true });

      const result = await caller.videoProject.deactivateShareToken({ tokenId: 10 });

      expect(result.success).toBe(true);
      expect(mockDeactivateShareToken).toHaveBeenCalledWith(10, 1);
    });
  });

  describe("videoProject.listCollaborators", () => {
    it("should list collaborators for a project", async () => {
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1 });
      mockListCollaborators.mockResolvedValueOnce([
        { id: 5, userId: 2, role: "viewer", userName: "Collaborator User" },
      ]);

      const result = await caller.videoProject.listCollaborators({ projectId: 1 });

      expect(result).toHaveLength(1);
      expect(result[0].role).toBe("viewer");
    });

    it("should reject if user doesn't own the project", async () => {
      mockGetVideoProject.mockResolvedValueOnce(null);

      await expect(
        caller.videoProject.listCollaborators({ projectId: 999 })
      ).rejects.toThrow();
    });
  });

  describe("videoProject.removeCollaborator", () => {
    it("should remove a collaborator", async () => {
      mockRemoveCollaborator.mockResolvedValueOnce({ success: true });

      const result = await caller.videoProject.removeCollaborator({
        collaboratorId: 5,
        projectId: 1,
      });

      expect(result.success).toBe(true);
      expect(mockRemoveCollaborator).toHaveBeenCalledWith(5, 1, 1);
    });
  });

  describe("videoProject.sharedWithMe", () => {
    it("should list projects shared with the user", async () => {
      mockListSharedWithMe.mockResolvedValueOnce([
        {
          collaboratorId: 5,
          projectId: 1,
          role: "viewer",
          projectTitle: "Mars Storyboard",
          projectType: "storyboard",
          ownerName: "Test Creator",
          updatedAt: new Date(),
        },
      ]);

      const result = await caller2.videoProject.sharedWithMe();

      expect(result).toHaveLength(1);
      expect(result[0].projectTitle).toBe("Mars Storyboard");
      expect(result[0].role).toBe("viewer");
    });

    it("should return empty array when no shared projects", async () => {
      mockListSharedWithMe.mockResolvedValueOnce([]);

      const result = await caller2.videoProject.sharedWithMe();

      expect(result).toHaveLength(0);
    });
  });
});

// ─── Version History Tests ────────────────────────────────────────
describe("Version History Features", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("videoProject.listRevisions", () => {
    it("should list revisions for a project owned by user", async () => {
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1 });
      mockListRevisions.mockResolvedValueOnce([
        {
          id: 100,
          version: 3,
          source: "manual",
          changeNote: "Updated scene descriptions",
          userName: "Test Creator",
          createdAt: new Date(),
        },
        {
          id: 99,
          version: 2,
          source: "ai-refinement",
          changeNote: "AI refined visual descriptions",
          userName: "Test Creator",
          createdAt: new Date(),
        },
      ]);

      const result = await caller.videoProject.listRevisions({ projectId: 1 });

      expect(result).toHaveLength(2);
      expect(result[0].version).toBe(3);
      expect(result[1].source).toBe("ai-refinement");
    });

    it("should allow collaborator to list revisions", async () => {
      // Not owner
      mockGetVideoProject.mockResolvedValueOnce(null);
      // But is collaborator
      mockGetUserCollaboratorRole.mockResolvedValueOnce("viewer");
      mockListRevisions.mockResolvedValueOnce([
        { id: 100, version: 1, source: "manual", changeNote: "Initial", createdAt: new Date() },
      ]);

      const result = await caller2.videoProject.listRevisions({ projectId: 1 });

      expect(result).toHaveLength(1);
    });

    it("should reject if not owner or collaborator", async () => {
      mockGetVideoProject.mockResolvedValueOnce(null);
      mockGetUserCollaboratorRole.mockResolvedValueOnce(null);

      await expect(
        caller2.videoProject.listRevisions({ projectId: 999 })
      ).rejects.toThrow("Project not found or not authorized");
    });
  });

  describe("videoProject.getRevision", () => {
    it("should return a specific revision with data", async () => {
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1 });
      mockGetRevision.mockResolvedValueOnce({
        id: 100,
        version: 3,
        data: { title: "Mars", scenes: [{ sceneNumber: 1 }] },
        source: "manual",
        changeNote: "Updated",
        createdAt: new Date(),
      });

      const result = await caller.videoProject.getRevision({
        revisionId: 100,
        projectId: 1,
      });

      expect(result.id).toBe(100);
      expect(result.data).toBeDefined();
      expect(result.version).toBe(3);
    });

    it("should throw NOT_FOUND for nonexistent revision", async () => {
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1 });
      mockGetRevision.mockResolvedValueOnce(null);

      await expect(
        caller.videoProject.getRevision({ revisionId: 999, projectId: 1 })
      ).rejects.toThrow("Revision not found");
    });
  });

  describe("videoProject.revertToRevision", () => {
    it("should revert to a previous revision", async () => {
      const oldData = { title: "Old Version", scenes: [{ sceneNumber: 1 }] };
      mockGetVideoProject.mockResolvedValueOnce({
        id: 1,
        userId: 1,
        data: JSON.stringify({ title: "Current", scenes: [] }),
      });
      mockGetRevision.mockResolvedValueOnce({
        id: 98,
        version: 1,
        data: JSON.stringify(oldData),
      });
      mockGetLatestRevisionVersion.mockResolvedValueOnce(3);
      mockCreateRevision.mockResolvedValueOnce({ id: 101 });
      mockUpdateVideoProject.mockResolvedValueOnce({ success: true });

      const result = await caller.videoProject.revertToRevision({
        revisionId: 98,
        projectId: 1,
      });

      expect(result.success).toBe(true);
      expect(result.revertedToVersion).toBe(1);
      expect(mockCreateRevision).toHaveBeenCalledWith(
        expect.objectContaining({
          projectId: 1,
          source: "revert",
        })
      );
      expect(mockUpdateVideoProject).toHaveBeenCalled();
    });

    it("should reject if user doesn't own the project", async () => {
      mockGetVideoProject.mockResolvedValueOnce(null);

      await expect(
        caller.videoProject.revertToRevision({ revisionId: 98, projectId: 999 })
      ).rejects.toThrow("Only the project owner can revert");
    });

    it("should reject if revision not found", async () => {
      mockGetVideoProject.mockResolvedValueOnce({ id: 1, userId: 1 });
      mockGetRevision.mockResolvedValueOnce(null);

      await expect(
        caller.videoProject.revertToRevision({ revisionId: 999, projectId: 1 })
      ).rejects.toThrow("Revision not found");
    });
  });
});

// ─── AI Refinement Tests ──────────────────────────────────────────
describe("AI Refinement Features", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("videoProject.refineProject", () => {
    it("should refine a storyboard project with feedback", async () => {
      mockGetVideoProject.mockResolvedValueOnce({
        id: 1,
        userId: 1,
        type: "storyboard",
        data: {
          title: "Mars Expedition",
          scenes: [{ sceneNumber: 1, visualDescription: "Original scene" }],
        },
      });

      const result = await caller.videoProject.refineProject({
        projectId: 1,
        feedback: "Make the transitions smoother and add more dramatic tension",
      });

      expect(result.status).toBe("completed");
      expect(result.projectType).toBe("storyboard");
      expect(result.originalData).toBeDefined();
      expect(result.refinedData).toBeDefined();
    });

    it("should refine with specific focus areas", async () => {
      mockGetVideoProject.mockResolvedValueOnce({
        id: 1,
        userId: 1,
        type: "script",
        data: {
          title: "Product Launch",
          scenes: [{ sceneNumber: 1, narration: "Original narration" }],
        },
      });

      const result = await caller.videoProject.refineProject({
        projectId: 1,
        feedback: "Improve the dialogue quality and pacing",
        focusAreas: ["Dialogue quality", "Pacing"],
      });

      expect(result.status).toBe("completed");
      expect(result.projectType).toBe("script");
    });

    it("should reject if project not found and not a collaborator", async () => {
      mockGetVideoProject.mockResolvedValueOnce(null);
      mockGetUserCollaboratorRole.mockResolvedValueOnce(null);

      await expect(
        caller.videoProject.refineProject({
          projectId: 999,
          feedback: "Improve everything please",
        })
      ).rejects.toThrow("Not authorized to refine this project");
    });
  });

  describe("videoProject.applyRefinement", () => {
    it("should apply refined data and create a new revision", async () => {
      const refinedData = {
        title: "Refined Mars Expedition",
        scenes: [{ sceneNumber: 1, visualDescription: "Improved scene" }],
      };

      mockGetVideoProject.mockResolvedValueOnce({
        id: 1,
        userId: 1,
        data: JSON.stringify({ title: "Old", scenes: [] }),
      });
      mockGetLatestRevisionVersion.mockResolvedValueOnce(2);
      mockCreateRevision.mockResolvedValueOnce({ id: 102 });
      mockUpdateVideoProject.mockResolvedValueOnce({ success: true });

      const result = await caller.videoProject.applyRefinement({
        projectId: 1,
        refinedData,
      });

      expect(result.success).toBe(true);
      expect(result.version).toBe(3);
      expect(mockCreateRevision).toHaveBeenCalledWith(
        expect.objectContaining({
          projectId: 1,
          source: "ai-refinement",
          version: 3,
        })
      );
      expect(mockUpdateVideoProject).toHaveBeenCalledWith(1, 1, {
        data: refinedData,
      });
    });

    it("should reject if project not found", async () => {
      mockGetVideoProject.mockResolvedValueOnce(null);

      await expect(
        caller.videoProject.applyRefinement({
          projectId: 999,
          refinedData: { title: "Test" },
        })
      ).rejects.toThrow("Project not found");
    });
  });
});
