import { Shield } from "lucide-react";

export default function DisclaimerBanner({ compact = false }: { compact?: boolean }) {
  if (compact) {
    return (
      <div className="flex items-center gap-2 px-3 py-1.5 rounded-md bg-primary/5 border border-primary/10">
        <Shield className="h-3.5 w-3.5 text-primary shrink-0" />
        <p className="text-[11px] text-muted-foreground">
          100% synthetic media — all content mathematically generated, no real individuals depicted or harmed.
        </p>
      </div>
    );
  }

  return (
    <div className="flex items-start gap-3 p-4 rounded-xl bg-primary/5 border border-primary/10">
      <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 shrink-0">
        <Shield className="h-4 w-4 text-primary" />
      </div>
      <div>
        <p className="text-sm font-medium text-foreground mb-1">
          100% Synthetic Media Research Platform
        </p>
        <p className="text-xs text-muted-foreground leading-relaxed">
          All content on this platform is mathematically generated by AI models. No real individuals
          are depicted or harmed. This platform exists exclusively for academic research into
          generative AI, synthetic content proliferation, and computational creativity.
        </p>
      </div>
    </div>
  );
}
