import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "AI Video Script Writer — Loglines, Beats & Full Scripts | DreamForgeX",
  description: "Turn a one-line concept into a production-ready video script: logline, three-act structure, scene beats, and dialogue generated by AI.",
  alternates: { canonical: "https://dreamforgex.ai/video-studio/script" },
  openGraph: {
    title: "AI Video Script Writer — DreamForgeX",
    description: "Concept to logline to full script — AI-written screenplays for your videos.",
  },
};
export default function Layout({ children }: { children: React.ReactNode }) { return children; }
